// Copyright 2024 Reece King (@kingmercian)
// SPDX-License-Identifier: GPL-2.0-or-later
#pragma once

#define SERIAL_PIO_USE_PIO1 // Force the usage of PIO1 peripheral, by default the Serial implementation uses the PIO0 peripheral

#define I2C_DRIVER I2CD1
#define I2C1_SDA_PIN GP2
#define I2C1_SCL_PIN GP3

#define SHOW_LOGO 4000
#define AUTO_SHIFT_TIMEOUT 200

// rgb
#ifdef RGB_MATRIX_ENABLE
#define RGBLIGHT_TIMEOUT 30000
#define RGB_MATRIX_LED_COUNT 70
#define RGB_MATRIX_STARTUP_VAL 120
#define NOP_FUDGE 0
#define RGB_MATRIX_SLEEP
#define RGB_MATRIX_STARTUP_MODE
#define RGB_MATRIX_LED_FLUSH_LIMIT 16
#define RGB_MATRIX_KEYPRESSES
#define RGB_MATRIX_KEYRELEASES
#define RGB_MATRIX_FRAMEBUFFER_EFFECTS

#define ENABLE_RGB_MATRIX_GRADIENT_UP_DOWN
#define ENABLE_RGB_MATRIX_GRADIENT_LEFT_RIGHT
#define ENABLE_RGB_MATRIX_ALPHAS_MODS
#define ENABLE_RGB_MATRIX_BREATHING
#define ENABLE_RGB_MATRIX_HUE_WAVE
#define ENABLE_RGB_MATRIX_RAINBOW_MOVING_CHEVRON
#define ENABLE_RGB_MATRIX_RAINBOW_BEACON

#if defined(RGB_MATRIX_KEYPRESSES) || defined(RGB_MATRIX_KEYRELEASES)
# define ENABLE_RGB_MATRIX_TYPING_HEATMAP
# define ENABLE_RGB_MATRIX_SOLID_REACTIVE_SIMPLE
# define ENABLE_RGB_MATRIX_SOLID_REACTIVE
# define ENABLE_RGB_MATRIX_SOLID_REACTIVE_WIDE
#endif
#endif

// i2c oled
#define OLED_FONT_H "libs/glcdfont.c"
#define OLED_FONT_WIDTH 6
#define OLED_FONT_HEIGHT 8
#define OLED_FONT_START 0
#define OLED_FONT_END 127
#define OLED_BRIGHTNESS 128
